apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: alpha
spec:
  containers:
    - name: testcontainer
      image: ubuntu
      command: ["sh", "-c", "tail -f /dev/null"]
  restartPolicy: Never
