apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          env:
            - name: PROTOCOL
              value: "https"
            - name: SERVICE_PORT
              value: "8443"
            - name: SERVICE_IP
              value: "127.0.0.1"
            - name: SERVICE_ADDRESS
              value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
          command: ["sh", "-c", "tail -f /dev/null"]

          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
      restartPolicy: Always
