apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      hostname: local
      containers:
        - name: ubuntu
          image: ubuntu
          command: ["/bin/sh"]
          args: ["-c", "tail -f /dev/null"]

          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
      restartPolicy: Always
